name: 3.3 Workflow multi-événements
on:
  push:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  triggered_by:
    runs-on: ubuntu-latest
    steps:
    - name: Afficher l'événement déclencheur
      run: echo "Le job a été déclenché par un événement de type ${{ github.event_name }}"
